version: '3'

services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-db:/data/db'

  flask:
    depends_on:
      - 'mongo'
    build: .
    ports:
      - '80:5000'
volumes:
  mongo-db:
