version: '3'

services:
  database:
    image: 'postgres:11'
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=tree-seg

  flask:
    depends_on:
      - 'database'
    build: .
    restart: unless-stopped
    ports:
      - '80:5000'

volumes:
  db:
